kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47.2,)
kff_version=4.11.0

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=hexex
mod_name=HexEX
mod_version=0.0.1-build0
mod_authors=Riii3393
mod_description=Hex Casting Extra Content
mod_license=MIT
# Used in maven publishing, should match mod sources: https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=io.github.riiimc.hexex
hex_version=0.11.3
paucalVersion=0.6.0-pre-118
caelusVersion=3.1.0+1.20
patchouliVersion=82
inlineVersion=1.20.1-1.0.1
clothConfigVersion=11.1.106
mantle_build=1.11.97
tinkers_build=3.11.1.158